name: couple_app
description: A couple management app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  google_sign_in: ^5.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
